make the logic more clear for the end user

diff --git a/spring-back-end/bin/ssl/enable-localhost-https b/spring-back-end/bin/ssl/enable-localhost-https
--- a/spring-back-end/bin/ssl/enable-localhost-https
+++ b/spring-back-end/bin/ssl/enable-localhost-https
@@ -54,16 +54,22 @@ while getopts "h" opt; do
 done
 
 echo
-read -r -p "Delete all files in ${SSL_KEYSTORE_DIR}?"
-select yn in "Yes" "No"; do
-  case $yn in
-  Yes)
-    rm "${SSL_KEYSTORE_DIR}"/*
-    break
-    ;;
-  No) ;;
-  esac
-done
+
+read -r -p "Delete all files in ${SSL_KEYSTORE_DIR}? (y/n) " yn
+case $yn in
+y | Y)
+  echo "Removing files from ${SSL_KEYSTORE_DIR}..."
+  rm "${SSL_KEYSTORE_DIR}"/*
+  ;;
+n | N)
+  echo "Proceeding without deleting files..."
+  ;;
+*)
+  echo "invalid response"
+  exit 1
+  ;;
+esac
+
 echo
 
 RSA_KEY_NAME=rootCA.key
